### ISSUE TITLE
Cannot use fastmat with numpy 2.1.3 on python 3.12, cannot install from source either

### ISSUE THREAD

**Issue by 3ddP** [EMS-TU-Ilmenau/fastmat#124]
The following problem has been experienced in WSL Ubuntu 22.04.03 LTS and WSL Ubuntu 22.04.05 LTS, with `conda` and with `venv`. The issue also occurs if numpy is installed via `conda` before `pip install`ing `fastmat`. 

- In a clean environment in which only `pip install fastmat` has been run, attempting to import `Toeplitz` from `fastmat` results in the following error:

```
Python 3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:27:36) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> from fastmat import Toeplitz
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/edd/anaconda3/envs/fm/lib/python3.12/site-packages/fastmat/__init__.py", line 53, in <module>
    from .Matrix import Matrix, Hermitian, Conjugate, Transpose, flags
  File "fastmat/Matrix.pyx", line 1, in init fastmat.Matrix
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

- Attempting to instead download the source and install via `pip install .` as per the instructions in the `README` results in a huge number of warnings and errors. A small excerpt is included at the end of the issue.

```
Error compiling Cython file:
      ------------------------------------------------------------
      ...


      ################################################## type handling

      cdef INFO_TYPE_s typeInfo[NUM_TYPES]
      cdef ftype typeSelection[<int> np.NPY_NTYPES]
                                       ^
      ------------------------------------------------------------

      fastmat/core/types.pxd:161:33: Not allowed in a constant expression

      Error compiling Cython file:
      ------------------------------------------------------------
      ...


      ################################################## type handling

      cdef INFO_TYPE_s typeInfo[NUM_TYPES]
      cdef ftype typeSelection[<int> np.NPY_NTYPES]
                              ^
      ------------------------------------------------------------

      fastmat/core/types.pxd:161:24: Variable type 'ftype []' is incomplete
      Traceback (most recent call last):
        File "/home/edd/fastmat-stable/.eggs/Cython-3.0.11-py3.12-linux-x86_64.egg/Cython/Build/Dependencies.py", line 1345, in cythonize_one_helper
          return cythonize_one(*m)
                 ^^^^^^^^^^^^^^^^^
        File "/home/edd/fastmat-stable/.eggs/Cython-3.0.11-py3.12-linux-x86_64.egg/Cython/Build/Dependencies.py", line 1321, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: fastmat/BlockDiag.pyx
      Traceback (most recent call last):
        File "/home/edd/fastmat-stable/.eggs/Cython-3.0.11-py3.12-linux-x86_64.egg/Cython/Build/Dependencies.py", line 1345, in cythonize_one_helper
          return cythonize_one(*m)
                 ^^^^^^^^^^^^^^^^^
        File "/home/edd/fastmat-stable/.eggs/Cython-3.0.11-py3.12-linux-x86_64.egg/Cython/Build/Dependencies.py", line 1321, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: fastmat/Circulant.pyx
      Traceback (most recent call last):
        File "/home/edd/fastmat-stable/.eggs/Cython-3.0.11-py3.12-linux-x86_64.egg/Cython/Build/Dependencies.py", line 1345, in cythonize_one_helper
          return cythonize_one(*m)
                 ^^^^^^^^^^^^^^^^^
        File "/home/edd/fastmat-stable/.eggs/Cython-3.0.11-py3.12-linux-x86_64.egg/Cython/Build/Dependencies.py", line 1321, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: fastmat/Diag.pyx
      Traceback (most recent call last):
        File "/home/edd/fastmat-stable/.eggs/Cython-3.0.11-py3.12-linux-x86_64.egg/Cython/Build/Dependencies.py", line 1345, in cythonize_one_helper
          return cythonize_one(*m)
                 ^^^^^^^^^^^^^^^^^
        File "/home/edd/fastmat-stable/.eggs/Cython-3.0.11-py3.12-linux-x86_64.egg/Cython/Build/Dependencies.py", line 1321, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: fastmat/Blocks.pyx
```

**Comment by ChristophWWagner** [comment]
Still trying to get my head around this. After considering the numpy 2.0 migration guide, I would propose to introduce a breaking change such, that binds the major versions of python to numpy, i. e. like this:
 * Python 3.12 --> latest numpy 1.x
 * Python 3.13 --> numpy 2.x and so on

This would limit the use of fastmat and numpy 2.x to python 3.13 and newer and restricts python 3.12 and below to numpy 1.x
**The use of combinations such as np2.x+py3.12 or np1.x+py3.13 would not be possible**.

Since some major type changes are also introduced with numpy 2.x, I would also suggest to also move the fastmat minor version to 0.3 for numpy2 support.

Would this fix the issue or is this a too strict limitation?
If you see another path forward, please tell (also poking @SebastianSemper)

Cheers
Christoph

[1] https://numpy.org/devdocs/numpy_2_0_migration_guide.html
