### ISSUE TITLE
Include current version when building docs

### ISSUE THREAD

**Issue by ChristophWWagner** [EMS-TU-Ilmenau/fastmat#51]
The caption of the generated HTML documentation always reads 'fastmat 1.0'. Instead the current version tag should be read from /fastmat/version.py (this file gets maintained by setup.py and always reflects the package version)

We should fix this as fast as possible as it is bad when we can't distinguish different versions of the documentation

**Comment by ChristophWWagner** [comment]
Also, trying to build the doc using
```setup.py build_doc```

yields

```bash
$ python setup.py build_doc
Override of version string to '0.1.2.post1' (from .version file )
Set fastmat/version.py to '0.1.2'
Building fastmat v0.1.2.post1 for Linux.
Requirements for setup: []
Requirements for install: []
running build_doc
Traceback (most recent call last):
  File "setup.py", line 377, in <module>
    ext_modules=lazyCythonize(extensions)
  File "/home/nutzer/.local/lib/python2.7/site-packages/setuptools/__init__.py", line 140, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 970, in run_command
    cmd_obj = self.get_command_obj(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 846, in get_command_obj
    cmd_obj = self.command_obj[command] = klass(self)
  File "setup.py", line 239, in __init__
    super(OwnDoc, self).__init__(*args, **kwargs)
TypeError: super() argument 1 must be type, not classobj
```
pip dump: 
```
$ pip list
alabaster (0.7.12)
astroid (1.4.9)
Babel (2.6.0)
backports-abc (0.5)
backports.functools-lru-cache (1.5)
backports.shutil-get-terminal-size (1.0.0)
beautifulsoup4 (4.5.3)
certifi (2018.10.15)
chardet (3.0.4)
chrome-gnome-shell (0.0.0)
configparser (3.3.0.post2)
cryptography (1.7.1)
cycler (0.10.0)
Cython (0.25.2)
decorator (4.0.11)
docutils (0.14)
entrypoints (0.2.2.post2)
enum34 (1.1.6)
funcsigs (1.0.2)
functools32 (3.2.3.post2)
futures (3.0.5)
html5lib (0.999999999)
idna (2.7)
imagesize (1.1.0)
ipaddress (1.0.17)
ipykernel (4.5.2)
ipython (5.1.0)
ipython-genutils (0.1.0)
ipywidgets (5.2.2)
isort (4.2.5)
Jinja2 (2.10)
jsonschema (2.5.1)
jupyter-client (4.4.0)
jupyter-core (4.2.1)
keyring (10.1)
keyrings.alt (1.3)
kiwisolver (1.0.1)
LabTools (0.1)
lazy-object-proxy (1.2.2)
lxml (3.7.1)
MarkupSafe (1.1.0)
matplotlib (2.2.3)
mistune (0.7.3)
mock (2.0.0)
nbconvert (4.2.0)
nbformat (4.2.0)
notebook (4.2.3)
numpy (1.15.2)
packaging (18.0)
pathlib2 (2.1.0)
pbr (1.10.0)
pexpect (4.2.1)
pickleshare (0.7.4)
Pillow (4.0.0)
pip (9.0.1)
prompt-toolkit (1.0.9)
ptyprocess (0.5.1)
pyasn1 (0.1.9)
pycodestyle (2.4.0)
pycrypto (2.6.1)
pyflakes (1.3.0)
Pygments (2.2.0)
pygobject (3.22.0)
pygraphviz (1.4rc1)
pylint (1.6.5)
pyOpenSSL (16.2.0)
pyparsing (2.3.0)
python-dateutil (2.7.3)
pytz (2018.7)
pyxdg (0.25)
pyzmq (16.0.2)
requests (2.20.1)
roman (2.0.0)
scapy (unknown.version)
scipy (1.1.0)
scour (0.32)
SecretStorage (2.3.1)
setuptools (40.5.0)
simplegeneric (0.8.1)
singledispatch (3.4.0.3)
six (1.11.0)
snowballstemmer (1.2.1)
Sphinx (1.8.1)
sphinxcontrib-programoutput (0.8.dev20160801)
sphinxcontrib-websupport (1.1.0)
subprocess32 (3.5.3)
terminado (0.6)
tornado (4.4.3)
traitlets (4.3.1)
typing (3.6.6)
urllib3 (1.24.1)
virtualenv (15.1.0)
wcwidth (0.1.7)
webencodings (0.5)
wheel (0.29.0)
wrapt (1.9.0)
wxPython (3.0.2.0)
wxPython-common (3.0.2.0)
```

**Comment by SebastianSemper** [comment]
For me the current bugfix branch cythonizes, builds and sphinxes without
complaints. :-/
